# This is a workflow that is manually triggered to test the docker build

name: Manual workflow for docker

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners to check we are working ok
    - name: check
      run: echo "first job done!"
    # Install checkout the repo
    - uses: actions/checkout@v4
    # get node js
    - uses: actions/setup-node@v4
    - name: check node
      run: node –version